version: "3.9"
services:
  discordgods:
    hostname: discordgods
    build: .
    restart: always
    stop_signal: SIGINT
    environment:
      - MARIADB_HOST=discordgods-database
      - MARIADB_PORT=3306
    env_file:
      - database.env
      - gods.env
    networks:
      - discordgods-network
    depends_on:
        - "discordgods-database"
  discordgods-database:
    hostname: discordgods-database
    image: mariadb
    restart: always
    security_opt:
      - seccomp:unconfined
    env_file:
      - database.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
    networks:
      - discordgods-network
volumes:
  db-data:
networks:
  discordgods-network:
    name: discordgods-network
